### ISSUE TITLE
Tech Debt todo list

### ISSUE THREAD

**Issue by ramraj07** [ramraj07/ramrajv.com#27]
except: Manage a list of todo items to maintain the blog
- [x] Use issue labels as a way to set tags
- [x] ensure only owner created issues are made into PRs
- [ ] reduce blog post title font size in listing
- [x] The date should be issue creation date not currrent date
